# Практика 10

## Задание 1

In [1]:
from sklearn.datasets import load_breast_cancer

dataset = load_breast_cancer()

## Задание 2

In [2]:
data_col_names = dataset.feature_names
data = dataset.data
target = dataset.target

print(f'data_col_names: {data_col_names}\n')
print(f'data: {data}\n')

data_col_names: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

data: [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]



## Задание 3

In [3]:
import numpy as np
import pandas as pd
from numpy import linalg as LA

def custom_pca(initial_data, pс_number: int):
    df = pd.DataFrame(data=initial_data, columns=data_col_names)
    
    # нормализуем (вычитая для каждого значения в колонке среднее значения этой колонки)
    df = df - df.mean()
    numpy_arr = pd.DataFrame(df).to_numpy()
        
    # строим матрицу ковариации
    cov_matr = np.cov(numpy_arr, rowvar=False)
    
    # диагонализируем матрицу
    eigenvalues, eigenvectors = LA.eig(cov_matr)

    # сортируем векторы
    sorted_indexes = np.argsort(-eigenvalues)
    
    # оставляем N главных компонент
    pc_indexes = sorted_indexes[:pс_number]
    
    # оставляем N главных компонент    
    n_principal_components = eigenvectors[:, pc_indexes]

    # модифицируем исходные нормализованные данные
    dotted_data = np.dot(numpy_arr, n_principal_components)
    return dotted_data

## Задание 4

In [4]:
from sklearn.decomposition import PCA

def sklearn_pca(initial_data, pс_number: int):
    X = np.array(data)
    pca = PCA(n_components=pс_number)
    pca.fit(X)
    return pca.transform(data)

In [5]:
sklearn_pca(data, 2)

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [6]:
sklearn_pca(data, 3)

array([[1160.1425737 , -293.91754364,   48.57839763],
       [1269.12244319,   15.63018184,  -35.39453423],
       [ 995.79388896,   39.15674324,   -1.70975298],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718],
       [1124.85811531,   34.12922497,  -19.74208742],
       [-771.52762188,  -88.64310636,   23.88903189]])

In [7]:
sklearn_pca(data, 4)

array([[1160.1425737 , -293.91754364,   48.57839763,   -8.71197531],
       [1269.12244319,   15.63018184,  -35.39453423,   17.86128323],
       [ 995.79388896,   39.15674324,   -1.70975298,    4.1993401 ],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718,   -9.77188104],
       [1124.85811531,   34.12922497,  -19.74208742,  -23.66088144],
       [-771.52762188,  -88.64310636,   23.88903189,    2.54724855]])

## Задание 5

In [8]:
custom_pca(data, 2)

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [9]:
custom_pca(data, 3)

array([[1160.1425737 , -293.91754364,   48.57839763],
       [1269.12244319,   15.63018184,  -35.39453423],
       [ 995.79388896,   39.15674324,   -1.70975298],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718],
       [1124.85811531,   34.12922497,  -19.74208742],
       [-771.52762188,  -88.64310636,   23.88903189]])

In [10]:
custom_pca(data, 4)

array([[1160.1425737 , -293.91754364,   48.57839763,    8.71197531],
       [1269.12244319,   15.63018184,  -35.39453423,  -17.86128323],
       [ 995.79388896,   39.15674324,   -1.70975298,   -4.1993401 ],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718,    9.77188104],
       [1124.85811531,   34.12922497,  -19.74208742,   23.66088144],
       [-771.52762188,  -88.64310636,   23.88903189,   -2.54724855]])